
version: 0.0
os: windows
files:
  - source: \
  destination: C:\build
hooks:
BeforeInstall:
AfterInstall:
ApplicationStart:
  - location: ./Deploy.bat
timeout: 300
ValidateService:
  - location: ./AfterService.bat
timeout: 300