version: 0.2



phases:

  install:

    runtime-versions:

      dotnet: 2.2

  build:

    commands:

      - dotnet restore server/TestProjectServer/TestProjectServer.csproj

      - dotnet build server/TestProjectServer/TestProjectServer.csproj

      - dotnet publish server/TestProjectServer/TestProjectServer.csproj -o ../../gameWebServer/bin -r win-x64



      - dotnet restore server/TestInterServer/TestInterServer.csproj

      - dotnet build server/TestInterServer/TestInterServer.csproj

      - dotnet publish server/TestInterServer/TestInterServer.csproj -o ../../interServer/bin -r win-x64

  post_build:

    commands:

      - cp server/Scripts/Deploy.bat gameWebServer/

      - cp server/Scripts/config.txt gameWebServer/

      - cp server/Scripts/Deploy.bat interServer/

      - cp server/Scripts/config.txt interServer/

      - cp server/TestProjectServer/appspec.yml gameWebServer/

      - cp server/TestProjectServer/appspec.yml interServer/

artifacts:

  files:

    - '**/*'

    - 'Deploy.bat'

  name: bin_build

  secondary-artifacts:

    gamewebserver:

      files:

        - '**/*'

      name: gamewebserver_build-$(date +%Y-%m-%d)

      base-directory: 'gameWebServer'

    interserver:

      files:

        - '**/*'

      name: interServer_build-$(date +%Y-%m-%d)

      base-directory: 'interServer'